events { worker_connections 1024; }

http {
    include mime.types;
    default_type application/octet-stream;

    server {
        listen 80;

        # Frontend
        location / {
            proxy_pass http://frontend:3000;
            proxy_set_header Host $host;
        }

        location /api/patients {
            proxy_pass http://patient-service:8081;
            proxy_set_header Host patient-service;
        }

        location /api/appointments {
            proxy_pass http://appointment-service:8082;
            proxy_set_header Host appointment-service;
        }

        location /api/bills {
            proxy_pass http://billing-service:8083;
            proxy_set_header Host billing-service;
        }

        location /api/prescriptions {
            proxy_pass http://prescription-service:8084;
            proxy_set_header Host prescription-service;
        }

        location /api/lab-reports {
            proxy_pass http://lab-service:8085;
            proxy_set_header Host lab-service;
        }

        location /api/reviews {
            proxy_pass http://review-service:8086;
            proxy_set_header Host review-service;
        }
    }
}
