spring.datasource.url=jdbc:postgresql://patient-db:5432/patientdb
spring.datasource.username=patient_user
spring.datasource.password=patient_pass
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8081
